IF db_id('VINICIUSMAIAITIXDB_TEST') IS NULL
	CREATE DATABASE VINICIUSMAIAITIXDB_TEST 
GO

USE VINICIUSMAIAITIXDB_TEST
GO

CREATE TABLE Paciente
(
Id INTEGER IDENTITY(1,1),
Nome VARCHAR(100) NOT NULL,
DataNascimento DATE NOT NULL,

CONSTRAINT PK_PACIENTE PRIMARY KEY(Id) 
);

CREATE TABLE Consulta
(
Id INTEGER IDENTITY(1,1),
IdPaciente INTEGER NOT NULL,
DataHoraInicio DATETIME NOT NULL,
DataHoraFim DATETIME NOT NULL,
Observacoes VARCHAR(500),

CONSTRAINT PK_CONSULTA PRIMARY KEY (Id),
CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (IdPaciente) REFERENCES PACIENTE(Id)
);

